oauth:
  # google_oauth2:
  #   app_id: '698416601498.apps.googleusercontent.com'
  #   app_secret: 'P7v9tP6b5VB-fO2vIFYYyc2x'
  facebook:
    app_id: '479239208797115'
    app_secret: 'd29cad9cdd4aef6afafb0a8cce0ee618'
  odnoklassniki:
    app_id: '165808640'
    app_secret: '9457379F0D2052867A47D2C1'
    public_key: 'CBALADOKABABABABA'
  vkontakte:
    app_id: '3527937'
    app_secret: 'vOwG3f6Keu4cAZyu9KhI'

